### ISSUE TITLE
Get user info

### ISSUE THREAD

**Issue by GijsThonnon** [ramswaroop/jbot#16]
Is it possible to get the info of a user like email?
getUser().getProfile().getEmail() returns null

**Comment by ramswaroop** [comment]
Yes, that's because that particular slack RTM event which you're trying isn't returning an email in the response. The models are generic to hold all RTM responses.

I would be adding slack web apis in SlackService.java and then you can call
`slackService.getUserEmail()` or something and store it in-memory or somewhere and use it in your bot.

**Comment by ramswaroop** [comment]
See various [Slack RTM event responses](https://api.slack.com/events/channel_created).

**Comment by ramswaroop** [comment]
Issue fixed with this PR https://github.com/ramswaroop/jbot/pull/26
